---
# Enable EPEL on RHEL 9

- hosts: all
  become: yes
  tasks: 


  - name: Enable EPEL
    shell: |
      dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      dnf config-manager --set-enabled epel
    
