---

- hosts: all
  become: yes
  tasks:

    - name: Install Apache and PHP Packages
      package:
        name: 
          - "{{ apache_pkg }}"
          - "{{ php_pkg }}"
        state: latest
        update_cache: yes

    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
  