---

- hosts: all
  become: yes
  tasks:

    - name: Install Apache Package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    - name: Update Repository Index
      dnf:
        update_cache: yes

    - name: Add PHP support for Apache
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "RedHat"


