- hosts: localhost
  tasks: 

    - name: Install unzip
      package:
        name: unzip
        state: latest
    
    - name: Install Terraform
      unarchive: 
        src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_darwin_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: Kris
      