---

- hosts: all
  become: yes
  tasks:

    - name: Install Apache and PHP Packages for RedHat Servers
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: Install Apache2 and PHP Packages for Ubuntu Servers
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
  
    - name: Start Apache Service for RedHat Servers
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
