---
#########################################################
# All Hosts - Update Cache
#########################################################

- hosts: all
  become: true
  pre_tasks:

    - name: Update Repo Cache (RedHat)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "RedHat"
      
    - name: Update Repo Cache (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

#########################################################
# All Hosts - Add SSH Key for Simone
#########################################################

- hosts: all
  become: true
  pre_tasks:
    
    - name: Add SSH Key for Simone
      tags: always
      authorized_key:
        user: Simone 
        key: "{{ lookup('file', '/Users/Kris/LUIT/Keys/simone_key.pub') }}"

#########################################################
# Web Servers
#########################################################

- hosts: web_servers
  become: true
  tasks:

    - name: Install Apache and PHP Packages for RedHat Servers
      tags: apache, httpd, redhat
      dnf:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install Apache2 and PHP Packages for Ubuntu Servers
      tags: apache, apache2, ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
  
    - name: Start Apache Service for RedHat Servers
      tags: apache, httpd, redhat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
    
    - name: Copy HTML files for website (RedHat)
      tags: apache, httpd, apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

#########################################################
# Database Servers
#########################################################

- hosts: db_servers
  become: true
  tasks: 

  - name: Install MariaDB Package (RedHat)
    tags: mariadb, redhat, db
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Start MariaDB Service (RedHat)
    tags: mariadb, redhat, db
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: Install MariaDB Package (Ubuntu)
    tags: mariadb, ubuntu, db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

#########################################################
# File Servers
#########################################################

- hosts: file_servers
  become: true
  tasks:

    - name: Install Samba Package
      tags: samba
      package:
        name: samba
        state: latest
    
    - name: Start Samba Service
      tags: samba
      service:
        name: smb
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
